controller_groups:
  joint_position:
    # - franka_gripper
    # - franka_state_controller
    - joint_position_example_controller
  impedance:
    # - franka_gripper
    # - franka_state_controller
    - cartesian_impedance_example_controller
  force:
    # - franka_gripper
    # - franka_state_controller
    - force_example_controller
  effort:
    # - franka_gripper
    # - franka_state_controller
    - effort_joint_trajectory_controller
